version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - MODEL_URL=${MODEL_URL}
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_URL=${MODEL_URL}
    volumes:
      - ./temp_audio:/app/temp_audio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped